fixed issue with exporting output

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,8 +34,8 @@ runs:
        sudo mkdir -p $mountPath/boot || echo 1>&2 "ERROR: could not create the boot partition's mount directory $mountPath/boot"
        sudo mount -t vfat $boot $mountPath/boot || echo 1>&2 "ERROR: could not mount $boot device to $mountPath/boot"
        echo "Mounted Image Details:"
-       df -h $mountPoint/boot $mountPoint | sed -e "s#$(pwd)/##" || echo 1>&2 "ERROR: could not inspect mounted partitions at $mountPoint and $mountPoint"
+       df -h ${mountPoint}/boot ${mountPoint} | sed -e "s#$(pwd)/##" || echo 1>&2 "ERROR: could not inspect mounted partitions at $mountPoint and $mountPoint"
        echo "::set-output name=bootDeviceMapper::${blockDevices[0]}"
        echo "::set-output name=rootDeviceMapper::${blockDevices[1]}"
-       echo "::set-output name=bootMountPoint::${$mountPath/boot}"
-       echo "::set-output name=rootMountPoint::${$mountPoint}"
+       echo "::set-output name=bootMountPoint::${mountPath}/boot"
+       echo "::set-output name=rootMountPoint::${mountPoint}"
